import React, { useState, useEffect } from 'react';
import { Download, Eye, X, Star } from 'lucide-react';
// JSZip will be loaded dynamically when downloading
import { supabase } from './supabaseClient';

function Gallery({ isOpen, onClose, onSelectExtension }) {
  const [extensions, setExtensions] = useState([]);
  const [previewExtension, setPreviewExtension] = useState(null);

  useEffect(() => {
    if (isOpen) {
      fetchPublicExtensions();
    }
  }, [isOpen]);

  const fetchPublicExtensions = async () => {
    const { data, error } = await supabase
      .from('extensions')
      .select('*')
      .eq('is_public', true)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching public extensions:', error);
    } else {
      // Debug: Log the actual data received from database
      console.log('Gallery data received:', data?.slice(0, 2)); // Log first 2 items
      console.log('First item favorite_count:', data?.[0]?.favorite_count);
      
      // Use favorite_count column directly from extensions table (optimal performance)
      setExtensions(data);
    }
  };

  const createPreviewHtml = (extension) => {
    if (!extension || !extension.files) return '';

    const htmlFile = Object.keys(extension.files).find(name => name.endsWith('.html'));
    if (!htmlFile) {
      return '<div style="padding: 20px; font-family: Arial; color: #333;">Preview unavailable: No HTML file found.</div>';
    }

    let html = extension.files[htmlFile];
    const cssFile = Object.keys(extension.files).find(name => name.endsWith('.css'));
    const css = cssFile ? extension.files[cssFile] : '';

    html = html.replace(/<link.*rel=\"stylesheet\".*>/g, '');

    const fallbackCss = `
      body {
        margin: 0;
        padding: 10px;
        font-family: Arial, sans-serif;
        background-color: #ffffff;
        color: #333333;
      }
    `;
    const combinedCss = fallbackCss + '\n' + (css || '');

    if (html.includes('</head>')) {
      return html.replace('</head>', `<style>${combinedCss}</style></head>`);
    } else {
      return `<!DOCTYPE html><html><head><style>${combinedCss}</style></head><body>${html}</body></html>`;
    }
  };

  const handleDownload = async (extension) => {
    if (!extension || !extension.files) return;

    try {
      // Dynamically import JSZip only when downloading
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      const extensionVersion = extension.version || '1.0';
      const safeVersion = extensionVersion.replace(/\./g, '_');
      const folderName = `${extension.name.replace(/[^a-zA-Z0-9]/g, '_')}_v${safeVersion}`;
      
      Object.entries(extension.files).forEach(([filename, content]) => {
        if (content && typeof content === 'string' && content.trim()) {
          zip.file(`${folderName}/${filename}`, content);
        } else {
          console.warn(`Skipping file ${filename} - invalid content`);
        }
      });
      
      zip.file(`${folderName}/README.txt`, `${extension.name} v${extensionVersion}\n${extension.description}\n\nGenerated by PlugPress.org\n`);
      
      const content = await zip.generateAsync({ 
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level: 6 }
      });
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${extension.name.replace(/[^a-zA-Z0-9]/g, '_')}_v${safeVersion}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Download error:', err);
      alert('Failed to download plugin. Please try again.');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4">
      <div className="bg-neutral-950 rounded-lg p-8 max-w-4xl w-full relative border border-white/10 shadow-xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-white"
        >
          <X className="w-6 h-6" />
        </button>
        <h2 className="text-3xl font-bold text-white mb-8 text-center">Gallery</h2>
        <div className="space-y-4 max-h-[70vh] overflow-y-auto">
          {extensions && extensions.length > 0 ? (
            extensions.map((ext) => (
              <div key={ext.id} className="bg-white/10 backdrop-blur-lg rounded-xl p-4 border border-white/20 flex items-center justify-between">
                <div className="flex items-center space-x-4">
                  <div className="w-24 h-24 bg-gray-700 rounded-lg flex-shrink-0 flex items-center justify-center">
                    <iframe
                      srcDoc={createPreviewHtml(ext)}
                      style={{ width: '100%', height: '100%', border: 'none', borderRadius: '8px' }}
                      title={`Preview of ${ext.name}`}
                      sandbox="allow-scripts"
                    />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-white">{ext.name}</h3>
                    <p className="text-gray-400 text-sm truncate max-w-md">Prompt: {ext.prompt}</p>
                    <div className="flex items-center space-x-2 mt-2">
                      <Star className="w-4 h-4 text-gray-400" />
                      <span className="text-gray-400 text-sm">{ext.favorite_count || 0} favorites</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <button onClick={() => setPreviewExtension(ext)} className="p-2 bg-gray-700 rounded-full text-white hover:bg-gray-600">
                    <Eye className="w-5 h-5" />
                  </button>
                  <button onClick={() => onSelectExtension(ext)} className="p-2 bg-lime-400 rounded-full text-black hover:bg-lime-500">
                    <p>View</p>
                  </button>
                  <button onClick={() => handleDownload(ext)} className="p-2 bg-green-500 rounded-full text-white hover:bg-green-600">
                    <Download className="w-5 h-5" />
                  </button>
                </div>
              </div>
            ))
          ) : (
            <p className="text-center text-gray-400">No public extensions found.</p>
          )}
        </div>
      </div>

      {previewExtension && (
        <div className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-60 p-4">
          <div className="bg-neutral-900 rounded-lg shadow-2xl w-full max-w-lg relative border border-white/10">
            <div className="flex items-center justify-between p-4 border-b border-white/10">
              <h3 className="text-xl font-bold text-white">Preview: {previewExtension.name}</h3>
              <button onClick={() => setPreviewExtension(null)} className="text-gray-400 hover:text-white">
                <X className="w-6 h-6" />
              </button>
            </div>
            <div className="p-4 bg-white" style={{ height: '60vh' }}>
              <iframe
                srcDoc={createPreviewHtml(previewExtension)}
                style={{ width: '100%', height: '100%', border: 'none' }}
                title={`Preview of ${previewExtension.name}`}
                sandbox="allow-scripts allow-modals"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Gallery;
